version: '3'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:80"

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "1300:1300"
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydatabase

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
